# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
