SECRET_KEY='Random top secret key, that should pretty long.'
DB_NAME='geekbeacon'
DB_USER='geekbeacon_user'
DB_PASS='My voice is my passport, verify me.'
DB_HOST='localhost'

DJANGO_DIR='/srv/geekbeacon'
GUNICORN_SOCK='/srv/run'
SSL_CERTIFICATE='/srv/certs/geekbeacon.crt'
SSL_KEY='/srv/certs/geekbeacon.key'
STATIC_DIR='/srv/geekbeacon-static/'
MEDIA_DIR='/srv/geekbeacon-media/'
VENV_DIR='/srv/.venv/'
