# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170925_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField()),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ContentItem')),
            ],
            options={
                'db_table': 'content_feature_history',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('content', models.ManyToManyField(blank=True, to='content.ContentItem')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.MenuItem')),
            ],
            options={
                'db_table': 'content_menu_item',
            },
        ),
        migrations.RemoveField(
            model_name='contentlayout',
            name='layout_id',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='type_id',
        ),
        migrations.AddField(
            model_name='contentlayout',
            name='selected',
            field=models.CharField(choices=[('full', 'Full Width (No Sidebar)'), ('sidebar', 'Sidebar')], default='sidebar', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenttype',
            name='selected',
            field=models.CharField(choices=[('page', 'Page'), ('post', 'Post')], default='post', max_length=20),
            preserve_default=False,
        ),
    ]
