# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170925_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='layout',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='content.ContentLayout'),
            preserve_default=False,
        ),
    ]
