# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contentitem_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
