# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170925_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='content',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ContentItem'),
        ),
    ]
